all: lab3a lab3b lab3c lab3d lab3e lab3f lab3g

lab3a: lab3a.c swap.c
	gcc -ansi -pedantic -g -o lab3a lab3a.c swap.c

lab3b: lab3b.c
	gcc -ansi -pedantic -g -o lab3b lab3b.c

lab3c: lab3c.c
	gcc -ansi -pedantic -g -o lab3c lab3c.c

lab3d: lab3d.c
	gcc -ansi -pedantic -g -o lab3d lab3d.c

lab3e: lab3e.c
	gcc -ansi -pedantic -g -o lab3e lab3e.c

lab3f: lab3f.c
	gcc -ansi -pedantic -g -o lab3f lab3f.c

lab3g: lab3g.c
	gcc -ansi -pedantic -g -o lab3g lab3g.c

clean:
	rm *.c *.h lab3a lab3b lab3c lab3d lab3e lab3f lab3g
