lab4: lab4main.o linked_list.o
	gcc -ansi -pedantic -g -o lab4 lab4main.o linked_list.o

lab4main.o: lab4main.c
	gcc -ansi -pedantic -g -c lab4main.c

linked_list.o: linked_list.c
	gcc -ansi -pedantic -g -c linked_list.c

clean:
	rm *.o lab4
